server:
  port: 8070

eureka:
  instance:
    hostname: localhost
  client:
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
     defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

management:
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true

  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      probes:
        enabled: true